<?php
/***************************************************************************
	@extension	: Bestseller Product.
	@copyright	: Copyright (c) 2014 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/

?>
<style>
.std .products-grid { margin:0 auto; padding:0; list-style:none; }
.std .products-grid li { margin-left:0; padding:0; list-style:none; }
</style>
<?php
	$result = $this->getBestsellerProduct();
	$collection = Mage::getResourceModel('catalog/product_collection');
	$collection->addFieldToFilter('entity_id',array('in'=>$result))->load();
	$foundIds = array_intersect($result,array_keys($collection->toArray()));
	$result = array_values($foundIds);
	$upperLimit = ($this->getLimit()) ? $this->getLimit() : 1; 
	$_columnCount = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 1 ;
	$model = Mage::getModel('catalog/product');
	$enabled = Mage::getStoreConfig('bestseller/general/enabled'); 
	$products_price = Mage::getStoreConfig('bestseller/general/products_price');  
	$review = Mage::getStoreConfig('bestseller/general/review'); 
	$out_of_stoke = Mage::getStoreConfig('bestseller/general/out_of_stoke');   
	
?>

<?php if($enabled == 1): ?>
	<div class="page-title category-title">
		<h1><?php echo $this->getHeader(); ?></h1>
	</div>
	<?php if ($out_of_stoke == 0) { ?>
	  	<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
			<?php
			$i=0; $x = 1;
			for($cnt = 0; $cnt<count($result); $cnt++) {
				$_product = $model->load($result[$cnt]);  
				$visibility = $_product->getData('visibility');
				$status =  $_product->getData('status');
				$is_salable = $_product->getData('is_salable');
				if($status == 1 && $visibility == 4) {	 
					if ($is_salable == 1 ){  
						if($x <= $upperLimit) {
						
			?>
			<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 135,($this->getImageWidth()) ? $this->getImageWidth() : 135); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
				</a>
				<div  class="product-info">
					<h2 class="product-name">
						<a href="<?php echo $this->getBaseUrl().$_product['url_path'] ?>" title="<?php echo $this->htmlEscape($_product['name']) ?>"><?php echo $this->htmlEscape($_product['name']) ?></a>
					</h2>
					<?php 
						if($review == 1) {
							$_product = Mage::getModel('catalog/product')->load($_product->getId());
							echo $this->getReviewsSummaryHtml($_product, 'short'); 
						}
						if($products_price == 1) {
							$_product = Mage::getModel('catalog/product')->load($_product->getId());
								echo $this->getPriceHtml($_product, true); 
						}
					?>  
					<div class="actions" style="display:block !important">	
						<?php $addtocartval = $this->getAddToCart();
							if($addtocartval == 1){
								if($_product->isSaleable() && !$_product->canConfigure()): ?>
									<button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										<span><?php echo $this->__('Add to Cart') ?></span>
									</button>
								 <?php elseif($_product->isSaleable()): ?>
								     <button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										<span><?php echo $this->__('View Details')?></span>
									</button> 
								<?php else: ?>
									<span class="out-of-stock">
										<?php echo $this->__('Out of stock') ?>
									</span>
							<?php endif; }?>
				
							<ul class="add-to-links">
								<?php $wishlists = $this->getActive();
									if($wishlists == 1){
										if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="addWishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; }?>
							
					
								<?php $addtocompare = $this->getAddToCompare();
									if($addtocompare==1){
										if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><a href="<?php echo $_compareUrl; ?>" class="addCompare"><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; }?>
								
							</ul>	
								
					</div>
				</div>	
			</li>
		    <?php
			   	}
				$x++;
				}
		        }		
            } 
           ?>
        </ul>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php
        }
        else
        {
        ?>
		<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
			<?php
				$i=0; $x = 1;
				for($cnt = 0; $cnt<count($result); $cnt++){
					$_product = $model->load($result[$cnt]); 
					$visibility = $_product->getData('visibility');
	
					$status =  $_product->getData('status'); 
					if ($status == 1 && $visibility == 4){
						if($x <= $upperLimit)	 {
						
			?>
			<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 135,($this->getImageWidth()) ? $this->getImageWidth() : 135); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
				</a>
				
				<div class="product-info">
											
						<h2 class="product-name"><a href="<?php echo $this->getBaseUrl().$_product['url_path'] ?>" title="<?php echo $this->htmlEscape($_product['name']) ?>"><?php echo $this->htmlEscape($_product['name']) ?></a></h2>
										
						<?php 
						    if($review == 1) {
								$_product = Mage::getModel('catalog/product')->load($_product->getId());
								echo $this->getReviewsSummaryHtml($_product, 'short'); 
							}
							if($products_price == 1) {
								$_product = Mage::getModel('catalog/product')->load($_product->getId());
								echo $this->getPriceHtml($_product, true); 
							}
						?>                
					<div class="actions" style="display:block !important">	
						<?php $addtocartval = $this->getAddToCart();
							if($addtocartval == 1){
								if($_product->isSaleable() && !$_product->canConfigure()): ?>
									<button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										<span><?php echo $this->__('Add to Cart') ?></span>
									</button>
								 <?php elseif($_product->isSaleable()): ?>
								     <button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										<span><?php echo $this->__('View Details')?></span>
									</button> 
								<?php else: ?>
									<span class="out-of-stock">
										<?php echo $this->__('Out of stock') ?>
									</span>
							<?php endif; }?>
				
							<ul class="add-to-links">
								<?php $wishlists = $this->getActive();
									if($wishlists == 1){
										if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="addWishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; }?>
							
					
								<?php $addtocompare = $this->getAddToCompare();
									if($addtocompare==1){
										if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><a href="<?php echo $_compareUrl; ?>" class="addCompare"><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; }?>
								
							</ul>	
								
					</div>					
			
				</div>
				 
			</li>
			 <?php
									
				}
		        $x++;
                }
            } 
            ?>
        </ul>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php
        }
        ?>


 <?php endif; ?>