<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php if($this->enableForLogin() && $this->hasButtons()) : ?>
    <div class="pslogin-form pageform-login">

        <div class="spacer pslogin-clearfix"> 
            <table>
            	<tr>
            		<td><div class="border"></div></td>
            		<td class="w25 text_or"><?php echo $this->__('OR'); ?></td>
            		<td><div class="border"></div></td>
            	</tr>
            </table>
            <span class="xs"><?php echo $this->__('Login with your social account'); ?></span>
        </div>

        <div class="pslogin-buttons">
            <ul class="pslogin-clearfix">
            <?php foreach ($this->getPreparedButtons() as $button) : ?>
                <li class="<?php echo $button['type']; ?> <?php echo empty($button['visible'])? 'pslogin-hidden' : 'pslogin-visible'; ?>" <?php echo empty($button['visible'])? 'style="display: none;"' : ''; ?> title="<?php echo $this->escapeHtml($button['login_text']); ?>">
                    <a rel="nofollow" href="<?php echo $button['href']; ?>" data-width="<?php echo $button['popup_width']; ?>" data-height="<?php echo $button['popup_height']; ?>" data-loader="<?php echo $this->getLoaderUrl(); ?>">

                        <?php if($this->showLoginFullButtons()) : ?>
                            <?php if(!empty($button['image']['login'])) : ?>
                                <img src="<?php echo $this->escapeHtml($button['image']['login']); ?>" class="md" />
                                <span class="background xs">
                                    <span class="soc-li-icon">
                                        <?php echo !empty($button['image']['icon'])? '<img src="'. $this->escapeHtml($button['image']['icon']) .'" />' : ''; ?>
                                    </span>
                                </span>
                            <?php else : ?>
                                <span class="background">
                                    <span class="soc-li-icon">
                                        <?php echo !empty($button['image']['icon'])? '<img src="'. $this->escapeHtml($button['image']['icon']) .'" />' : ''; ?>
                                    </span>
                                    <span class="soc-li-text"><?php echo $this->escapeHtml($button['login_text']); ?></span>
                                </span>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if(!empty($button['image']['icon'])) : ?>
                                <img src="<?php echo $this->escapeHtml($button['image']['icon']); ?>" />
                            <?php else : ?>
                                <span class="background">
                                    <span class="soc-li-icon"></span>
                                    <span class="soc-li-text text-hidden"><?php echo $this->escapeHtml($button['login_text']); ?></span>
                                </span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>

            <?php if($this->getPreparedButtons('hidden')) : ?>
                <div class="spacer pslogin-clearfix show-hidden"> 
		            <table>
		            	<tr>
		            		<td><div class="border"></div></td>
		            		<td class="w100"><div id="psloginShowBtn" class="text_or"><?php echo $this->__('show more'); ?></div></td>
		            		<td><div class="border"></div></td>
		            	</tr>
		            </table>
                </div>
            <?php endif; ?>
        </div>

    </div>
    <div style="clear: both;"></div>
<?php endif; ?>